# hostname (and path) to the root
baseURL: "http://hugo.gomakethings.com"

# The language code for the site
languageCode: "en-us"

# Site title
title: "Go Make Things"

# theme to use (located by default in /themes/THEMENAME/)
theme: "gmt"

# Permalinks
# See "content-management/permalinks"
permalinks:
  articles: /:title/

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["RSS", "hugoGeneratorInject"]

# the length of text to show in a .Summary
summaryLength: 70

# Pagination
paginate: 35
paginatePath: "page"

# Markdown Options
blackfriday:
  fractions: false

# Site taxonomies
taxonomies:
  - category: "categories"
  - tag: "tags"

# Customer parameters
params:
  description: "Vanilla JavaScript for beginners and designers."
  rssURL: "http://feeds.feedburner.com/GoMakeThings"
  rssLimit: 7